In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression as lr

In [27]:
df=pd.read_csv("/content/drive/MyDrive/ml/carprices (1).csv")
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [28]:
df2=pd.get_dummies(df["Car Model"])
df=pd.concat([df,df2],axis=1)
df.drop(["Mercedez Benz C class","Car Model"], axis=1, inplace=True)
df

Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5
0     69000          18000         6        0       1
1     35000          34000         3        0       1
2     57000          26100         5        0       1
3     22500          40000         2        0       1
4     46000          31500         4        0       1
5     59000          29400         5        1       0
6     52000          32000         5        1       0
7     72000          19300         6        1       0
8     91000          12000         8        1       0
9     67000          22000         6        0       0
10    83000          20000         7        0       0
11    79000          21000         7        0       0
12    59000          33000         5        0       0

In [30]:
Y=df["Sell Price($)"]
X=df.drop(["Sell Price($)"],axis=1)
X,Y

(    Mileage  Age(yrs)  Audi A5  BMW X5
 0     69000         6        0       1
 1     35000         3        0       1
 2     57000         5        0       1
 3     22500         2        0       1
 4     46000         4        0       1
 5     59000         5        1       0
 6     52000         5        1       0
 7     72000         6        1       0
 8     91000         8        1       0
 9     67000         6        0       0
 10    83000         7        0       0
 11    79000         7        0       0
 12    59000         5        0       0, 0     18000
 1     34000
 2     26100
 3     40000
 4     31500
 5     29400
 6     32000
 7     19300
 8     12000
 9     22000
 10    20000
 11    21000
 12    33000
 Name: Sell Price($), dtype: int64)

In [32]:
mod=lr().fit(X,Y)
mod.coef_

array([-3.70122094e-01, -1.33245363e+03, -2.45354074e+03, -6.73820733e+03])

In [34]:
mod.predict([[33340,2,0,1]])

array([37233.64076074])

In [35]:
from sklearn.externals import joblib as jb
jb.dump(mod, "OHE_carprice")

/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


['OHE_carprice']

In [36]:
mod2=jb.load("OHE_carprice")

In [37]:
mod2.predict([[23005,9,0,0]])

array([38469.88453862])